/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.User',{
     extend: 'Ext.data.Model',
     alias: 'model.User',
 
       config: {
           fields: [
           {
              name: 'username'
           },
           {
              name: 'password'
           },
            {
              name: 'email'
           },
           {
              name: 'website'
           },
            {
              name: 'aboutyou'
           }
           ],
           validations: [
           {
              type: 'presence',
              field: 'username'
           },
           {
              type: 'presence',
              field: 'password'
           },
           {
              type: 'presence',
              field: 'email'
           },
           {
              type: 'presence',
              field: 'website'
           },
           {
              type: 'format',
              field: 'username',
              matcher: /[0-9A-Za-z]{6,15}/,
              message: 'Username should be alphanumeric'
           },
            {
              type: 'length',
              field: 'password',
              min: 6,
            message: 'Password must contain min 6 characters'
           },
            {
              type: 'email',
              field: 'email',
            message: 'Email format is invalid'
           }]
     }
});